### PR TITLE
Fixed Wind using wrong decimal separator

### PR DESCRIPTION
**Pull request by iminet**
Changed the numeric values' `CultureInfo.InvariantCulture` to `CultureInfo.CurrentCulture` to keep the decimal separator in the right place.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Hi, I think this issue was resolved over in https://github.com/swiftyspiffy/OpenWeatherMap-API-CSharp/pull/21 . Feel free to reopen though.

**Comment by drenkmann** [comment]
I don't think I fixed it for the wind, so this might still be relevant.

**Comment by iminet** [comment]
> I don't think I fixed it for the wind, so this might still be relevant.

@swiftyspiffy FYI

**Comment by iminet** [comment]
I can't reopen the PR (there's no `reopen` button), what about you @swiftyspiffy?
Thanks.

**Pull request closed without merging**
